import { Staff } from '../types';

export const STAFF_IMAGE_PLACEHOLDER = 'https://assets.syncrozz.com/placeholder/staff.webp';

/**
 * Normalizes staff ID (e.g. ST001, STF-001 -> ST001)
 */
export const formatStaffId = (rawId: string): string => {
  if (!rawId) return 'ST000';
  const cleaned = rawId.trim().toUpperCase().replace(/^STF-/i, 'ST').replace(/^STF/i, 'ST');
  return cleaned || rawId.trim();
};

/**
 * Returns the automatic SYNCROZZ Assets profile image URL for a staff member.
 * Format: https://assets.syncrozz.com/profile/staff/{staff_id}.webp
 */
export const getStaffImageUrl = (staffId?: string): string => {
  if (!staffId) return STAFF_IMAGE_PLACEHOLDER;
  const cleanId = formatStaffId(staffId);
  return `https://assets.syncrozz.com/profile/staff/${cleanId}.webp`;
};

/**
 * Returns image candidate array:
 * Primary SYNCROZZ URL -> SYNCROZZ Placeholder URL
 * Always generated by https://assets.syncrozz.com/profile/staff/{staff_id}.webp
 */
export const getStaffPhotoCandidates = (staff: Staff): string[] => {
  const id = staff?.staff_id || staff?.ID || '';
  const primaryUrl = getStaffImageUrl(id);
  return [primaryUrl, STAFF_IMAGE_PLACEHOLDER];
};

export const getInitials = (name: string): string => {
  if (!name) return 'ST';
  const cleanName = name
    .replace(/^(Tuan|Haji|Puan|Encik|Dr\.|Cik|Hj\.|Pn\.|En\.)\s+/i, '')
    .replace(/\s+(Cmilt|M\.T\.A\.M|C\.A\.\(M\)|Afpm)$/i, '')
    .replace(/^(bin|binti|bt|bt\.)\s+/i, '');
  const parts = cleanName.split(/\s+/).filter(Boolean);
  if (parts.length === 0) return 'ST';
  if (parts.length === 1) return parts[0].substring(0, 2).toUpperCase();
  return (parts[0][0] + parts[1][0]).toUpperCase();
};

